# Organic
string vessel
float64 pressure
float64 temp
float64 time
float64 stir_speed
---
bool success
---
string status
string current_device
builtin_interfaces/Duration time_spent
builtin_interfaces/Duration time_remaining
