# Bio
# 请求字段
Resource plate
Resource to
geometry_msgs/Point[] intermediate_locations
geometry_msgs/Point resource_offset
geometry_msgs/Point pickup_offset
geometry_msgs/Point destination_offset
string pickup_direction
string drop_direction
string get_direction
string put_direction
float64 pickup_distance_from_top
---
# 结果字段
bool success
---
# 反馈字段 