Resource[] resources
float64[] vols
int32[] use_channels
float64[] flow_rates
geometry_msgs/Point[] offsets
float64[] liquid_height
float64[] blow_out_air_volume
string spread="wide"
---
bool success
---