@echo off
set AMENT_PREFIX_PATH_BACKUP=%AMENT_PREFIX_PATH%
set AMENT_PREFIX_PATH=%CONDA_PREFIX%\Library
set PATH=%CONDA_PREFIX%\Library\bin;%PATH%
set CMAKE_PREFIX_PATH=%CONDA_PREFIX%\Library;%CMAKE_PREFIX_PATH%
set PYTHONPATH=%CONDA_PREFIX%\Lib\site-packages;%PYTHONPATH%