@echo off
set AMENT_PREFIX_PATH=%AMENT_PREFIX_PATH_BACKUP%
set AMENT_PREFIX_PATH_BACKUP=
set PATH=%PATH:%CONDA_PREFIX%\Library\bin;=%
set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH:%CONDA_PREFIX%\Library;=%
set PYTHONPATH=%PYTHONPATH:%CONDA_PREFIX%\Lib\site-packages;=%